#--------------------------------------
# èœå•é…ç½®è¯´æ˜
# identifier ï¼š å”¯ä¸€æ ‡è¯†ä¸å¯é‡å¤
# name       ï¼š èœå•æ˜¾ç¤ºåç§°
# pageref    ï¼š æœ¬ç«™ç‚¹é“¾æ¥åœ°å€ï¼Œä¸ URL é€‰å…¶ä¸€
# url        ï¼š ç«™ç‚¹å¤–éƒ¨é“¾æ¥åœ°å€ï¼Œä»¥ http æˆ–è€… https å¼€å¤´
# pre        ï¼š èœå•å°å›¾æ ‡
# weight     ï¼š æ˜¾ç¤ºé¡ºåºï¼Œå­—æ•°è¶Šå°è¶Šé å‰
# 
# Menus Settings
# identifier : Unique ID cannot be repeated
# name       : Menu name
# pageref    : Link of webiste and not appeare same time with url
# url        : Exteneral link out of website and start with http or https
# pre        : Icon of menu
# weight     : Order number and smaller is top
# -------------------------------------
main:
  - identifier: home
    name: é¦–é¡µ
    pageref: /
    pre: home
    weight: 1
  - identifier: about
    name: å…³äº
    pageref: /about.html
    pre: user
    weight: 2
  - identifier: sillyGirl
    name: å‚»å¦ä¸“é¢˜
    pageref: /sillyGirl
    pre: ğŸ‘§
    weight: 3
  - identifier: archives
    name: å½’æ¡£
    pageref: /archives
    pre: archive
    weight: 4
  - identifier: commonweal
    name: å…¬ç›Š 404
    url: /404.html
    pre: heartbeat
    weight: 5